/**
 * Installing Grok (epic 12 entry 4): the pinned `@xai-official/grok` package
 * and this computer's platform package into `<dataDir>/agents/grok/` by the
 * shared pinned-npm installer (`pinned-npm/install.ts`): `npm ci` from the
 * pinned lock, `--ignore-scripts`, every tarball's integrity checked, nothing
 * installed globally, `~/.grok` never read or written.
 *
 * npm's own launcher (`bin/grok`) and its postinstall never run (spike 12.2,
 * "pinning trap": the launcher prefers `$GROK_HOME/bin/grok`, then installs
 * there, so a user's own self-updated `grok` would silently replace the
 * pinned one). Instead, the platform package carries the binary brotli
 * compressed (`bin/grok[.exe].br`): Ogden decompresses it itself into
 * `bin-checked/grok[.exe]` inside the version folder, checks its SHA-256
 * against the pin in `acp-grok/constants.ts` (xAI publishes none, so the
 * pin is Ogden's own, recorded from the real packages), and refuses the
 * whole install when it does not match. The chat adapter spawns only that file.
 */
import { grokAcceptsToken } from './token-probe.js';
import { renameWithRetry } from '../toolchain-uv/uv-toolchain.js';
import { chmodSync, closeSync, createReadStream, createWriteStream, existsSync, lstatSync, mkdirSync, openSync, readdirSync, readFileSync, readSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { Transform } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { createBrotliDecompress } from 'node:zlib';
import { AgentSetupError, type AgentPlatform } from '@ogden-agents/core';
import { GROK, GROK_BINARY_PREFIX, GROK_BINARY_SCOPE, GROK_BINARY_SHA256, GROK_PACKAGE } from '../acp-grok/constants.js';
import {
  installPinnedNpm,
  pinnedVersionOf,
  removeStalePinnedInstalls,
  type AdapterLock,
  type AdapterPins,
  type InstallPinnedNpmOptions,
  type InstallWords,
  type PinnedNpmSpec,
} from '../pinned-npm/install.js';
import pinnedLock from './pins/package-lock.json' with { type: 'json' };
import pinnedManifest from './pins/package.json' with { type: 'json' };

/** `<dataDir>/agents/grok`: the installed copies and the temp folders an install works in. */
export const GROK_DIR = join('agents', 'grok');

/** The pinned package and its platform packages (`pins/`, generated by `scripts/agent-pins.mjs --agent grok`). */
export const GROK_PINS: AdapterPins = { packageJson: pinnedManifest, lock: pinnedLock as AdapterLock };

/** The folder inside an installed copy that holds the checked binary. */
export const GROK_CHECKED_DIR = 'bin-checked';

/** The checked binary's file name on `platform`. */
const binaryName = (platform: string) => (platform.startsWith('win32') ? 'grok.exe' : 'grok');

/** The most the decompressed binary may be: well above the real ones (about 175 MB), well below a decompression bomb. */
export const GROK_MAX_BINARY_BYTES = 400 * 1024 * 1024;

/** `grok-<version>`; a prerelease (`0.0.0-fixture`) is a version too. */
const INSTALLED_FOLDER = /^grok-(\d+\.\d+\.\d+(?:-[0-9A-Za-z.]+)?)$/;

/** Whether the lock holds Grok's platform binary packages (the real pins do; a test fixture needn't). */
const locksBinaries = (lock: AdapterLock) => Object.keys(lock.packages).some((path) => path.startsWith(`node_modules/${GROK_BINARY_SCOPE}/${GROK_BINARY_PREFIX}`));

const platformPackage = (platform: string) => `${GROK_BINARY_SCOPE}/${GROK_BINARY_PREFIX}${platform}`;

/** Whether npm put this computer's platform package in `project`. */
const hasBinary = (project: string): boolean => existsSync(join(project, 'node_modules', ...platformPackage(`${process.platform}-${process.arch}`).split('/')));

/** What an install checks the binary against: the pins, or (tests) another table. */
export type GrokBinaryHashes = Readonly<Partial<Record<AgentPlatform, string>>>;

/**
 * Decompresses `source` (a brotli file) to `target`, hashing as it goes and refusing more than
 * {@link GROK_MAX_BINARY_BYTES}; resolves with the SHA-256 of what was written. Nothing is kept on failure.
 */
export async function decompressBinary(source: string, target: string, maxBytes = GROK_MAX_BINARY_BYTES, signal?: AbortSignal): Promise<string> {
  const hash = createHash('sha256');
  let bytes = 0;
  const watch = new Transform({
    transform(chunk: Buffer, _encoding, callback) {
      bytes += chunk.length;
      if (bytes > maxBytes) return callback(new Error('too_large'));
      hash.update(chunk);
      callback(null, chunk);
    },
  });
  try {
    await pipeline(createReadStream(source), createBrotliDecompress(), watch, createWriteStream(target, { mode: 0o700, flags: 'wx' }), signal === undefined ? {} : { signal });
  } catch (error) {
    rmSync(target, { force: true });
    throw error;
  }
  return hash.digest('hex');
}

/** The finalize step: this platform's binary, decompressed into `<project>/bin-checked/`, checked, executable. */
function finalizeFor(hashes: GrokBinaryHashes, probe: (binary: string) => Promise<boolean>) {
  return async (project: string, words: InstallWords, options: Pick<InstallPinnedNpmOptions, 'signal' | 'onProgress'>): Promise<void> => {
    const platform = `${process.platform}-${process.arch}` as AgentPlatform;
    const pinned = hashes[platform];
    if (pinned === undefined) throw new AgentSetupError(words.noBinary, { details: { step: 'binary', platform: process.platform, arch: process.arch } });
    const aborted = () => options.signal?.aborted === true;
    if (aborted()) throw new AgentSetupError(words.stopped, { details: { step: 'binary', stopped: true } });
    options.onProgress({ step: words.checking, percent: 96 });
    const compressed = join(project, 'node_modules', ...platformPackage(platform).split('/'), 'bin', `${binaryName(platform)}.br`);
    // Only a plain file the package carries: a link in its place is never followed.
    let plain = false;
    try {
      plain = lstatSync(compressed).isFile();
    } catch {
      plain = false;
    }
    if (!plain) throw new AgentSetupError(words.notRight, { details: { step: 'binary', missing: true } });
    const dir = join(project, GROK_CHECKED_DIR);
    mkdirSync(dir, { recursive: true });
    const unchecked = join(dir, `${binaryName(platform)}.part`);
    const target = join(dir, binaryName(platform));
    let sha256: string;
    try {
      sha256 = await decompressBinary(compressed, unchecked, GROK_MAX_BINARY_BYTES, options.signal);
    } catch (error) {
      if (aborted()) throw new AgentSetupError(words.stopped, { details: { step: 'binary', stopped: true } });
      throw new AgentSetupError(words.notRight, { details: { step: 'binary', code: (error as Error).message === 'too_large' ? 'too_large' : String((error as NodeJS.ErrnoException).code ?? 'unknown').slice(0, 40) }, cause: error });
    }
    if (sha256 !== pinned) {
      rmSync(unchecked, { force: true });
      throw new AgentSetupError(words.mismatch, { details: { step: 'binary', mismatch: true } });
    }
    try {
      // A freshly written binary can be held by an antivirus scan on Windows: retried as the folder swap is.
      await renameWithRetry(unchecked, target, 10);
      if (process.platform !== 'win32') chmodSync(target, 0o755);
      // What was checked, for a later release that moves the pin while this install keeps working (see `grokBinaryUnchanged`).
      writeFileSync(`${target}${GROK_CHECK_RECORD_SUFFIX}`, `${sha256}\n`);
    } catch (error) {
      rmSync(unchecked, { force: true });
      throw new AgentSetupError(words.couldNotPlace, { details: { step: 'binary', code: String((error as NodeJS.ErrnoException).code ?? 'unknown').slice(0, 40) }, cause: error });
    }
    options.onProgress({ step: words.checking, percent: 98 });
    // The unadvertised `xai.api_key` method is the only way in (user decision, 2026-10-05): a version that drops it can't be used, so nothing is installed.
    if (!(await probe(target))) throw new AgentSetupError(NO_TOKEN_METHOD, { details: { step: 'token_method', accepted: false } });
  };
}

/** What Install says when the unpacked Grok no longer takes an xAI API access token. */
export const NO_TOKEN_METHOD = "Grok didn't accept an xAI API access token the way Ogden Agents needs, or didn't answer in time, so nothing was installed. Try again.";

/** Asks the checked binary whether it accepts a token (tests: a stub; the default spawns it, see `token-probe.ts`). */
export type GrokTokenProbe = (binary: string) => Promise<boolean>;

/** How Grok is installed, for the shared installer. `hashes` is the table the binary is checked against. */
export function grokInstallSpec(hashes: GrokBinaryHashes = GROK_BINARY_SHA256, probe: GrokTokenProbe = grokAcceptsToken): PinnedNpmSpec {
  return {
    displayName: GROK,
    dir: GROK_DIR,
    packageName: GROK_PACKAGE,
    // npm's launcher: only proves the package installed; it is never run.
    entry: ['bin', 'grok'],
    folderName: (version) => `grok-${version}`,
    isInstalledFolder: (name) => INSTALLED_FOLDER.test(name),
    binary: { locked: locksBinaries, present: hasBinary },
    finalize: finalizeFor(hashes, probe),
    resultPath: (folder) => join(folder, GROK_CHECKED_DIR, binaryName(`${process.platform}-${process.arch}`)),
  };
}

/** Grok's install spec with the real pins' hashes. */
export const GROK_INSTALL_SPEC: PinnedNpmSpec = grokInstallSpec();

/** The package version `pins` installs. */
export function pinnedGrokVersion(pins: AdapterPins = GROK_PINS): string {
  return pinnedVersionOf(GROK_INSTALL_SPEC, pins);
}

/** The file beside the checked binary that records the SHA-256 the install checked (its name is the binary's plus this). */
export const GROK_CHECK_RECORD_SUFFIX = '.sha256';

const SHA256_HEX = /^[0-9a-f]{64}$/;

/** Binaries already re-checked in this process, by what identifies this file's state (size, inode, change and modify times). */
const rechecked = new Map<string, string>();

function sha256OfFile(path: string): string {
  const hash = createHash('sha256');
  const fd = openSync(path, 'r');
  try {
    const buffer = Buffer.allocUnsafe(1 << 20);
    for (let read = readSync(fd, buffer, 0, buffer.length, null); read > 0; read = readSync(fd, buffer, 0, buffer.length, null)) hash.update(buffer.subarray(0, read));
  } finally {
    closeSync(fd);
  }
  return hash.digest('hex');
}

/**
 * Whether the checked binary is still the one the install checked (AD-16, 12.4 review): its SHA-256 against the
 * pinned table for the pinned version, else against the record the install wrote beside it. Hashed in full the
 * first time in a server run, then not again while the file's size, inode and change time stand (the change time
 * moves when the file's content or metadata does, and no user program can set it back). A binary with no pin and
 * no record, or any read failure, is not trusted. Synchronous: `launch` is.
 */
export function grokBinaryUnchanged(grok: InstalledGrok, hashes: GrokBinaryHashes = GROK_BINARY_SHA256, pinnedVersion: string = pinnedGrokVersion()): boolean {
  try {
    const info = statSync(grok.path);
    if (!info.isFile()) return false;
    const state = `${info.size}:${info.ino}:${info.ctimeMs}:${info.mtimeMs}`;
    if (rechecked.get(grok.path) === state) return true;
    const platform = `${process.platform}-${process.arch}` as AgentPlatform;
    let expected: string | undefined;
    if (grok.version === pinnedVersion) expected = hashes[platform];
    else {
      const recorded = readFileSync(`${grok.path}${GROK_CHECK_RECORD_SUFFIX}`, 'utf8').trim();
      expected = SHA256_HEX.test(recorded) ? recorded : undefined;
    }
    if (expected === undefined || sha256OfFile(grok.path) !== expected) {
      rechecked.delete(grok.path);
      return false;
    }
    rechecked.set(grok.path, state);
    return true;
  } catch {
    return false;
  }
}

export interface InstalledGrok {
  /** The checked binary, `…/grok-<version>/bin-checked/grok[.exe]`: the only file Ogden ever spawns. */
  path: string;
  version: string;
}

/**
 * The binary an install put in `<dataDir>/agents/grok/`, or `undefined`: the pinned
 * version first, then the newest other (a release that bumps the pin keeps an earlier
 * install working).
 */
export function installedGrok(dataDir: string, pins: AdapterPins = GROK_PINS): InstalledGrok | undefined {
  const dir = join(dataDir, GROK_DIR);
  let names: string[];
  try {
    names = readdirSync(dir);
  } catch {
    return undefined;
  }
  const pinned = pinnedGrokVersion(pins);
  return names
    .map((name) => ({ name, match: INSTALLED_FOLDER.exec(name) }))
    .filter((entry): entry is { name: string; match: RegExpExecArray } => entry.match !== null)
    .map(({ name, match }) => ({ path: GROK_INSTALL_SPEC.resultPath!(join(dir, name)), version: match[1]! }))
    .filter((grok) => existsSync(grok.path))
    .sort((a, b) => {
      if ((a.version === pinned) !== (b.version === pinned)) return a.version === pinned ? -1 : 1;
      return b.version.localeCompare(a.version, 'en', { numeric: true });
    })[0];
}

export type InstallGrokOptions = Omit<InstallPinnedNpmOptions, 'pins' | 'withBinary'> & {
  pins?: AdapterPins | undefined;
  /** The binary hashes to check against (tests: a fixture binary's). Default: the pinned ones. */
  binarySha256?: GrokBinaryHashes | undefined;
  /** Asks the unpacked binary whether it takes a token. Default: the real check; tests (and the fixture hook) pass a stub, so no fixture binary is ever run. */
  tokenProbe?: GrokTokenProbe | undefined;
};

/**
 * Installs the pinned package and this computer's checked binary under
 * `<dataDir>/agents/grok/`, reporting progress; rejects with an `AgentSetupError`
 * in plain words, leaving nothing half installed (the shared installer's rules).
 */
export async function installGrok(options: InstallGrokOptions): Promise<InstalledGrok> {
  const { binarySha256, tokenProbe, ...rest } = options;
  const spec = binarySha256 === undefined && tokenProbe === undefined ? GROK_INSTALL_SPEC : grokInstallSpec(binarySha256 ?? GROK_BINARY_SHA256, tokenProbe);
  return installPinnedNpm(spec, { ...rest, pins: options.pins ?? GROK_PINS, withBinary: true });
}

/** Removes the `.install-*` folders a crashed or killed install left in `<dataDir>/agents/grok/` (server start). */
export function removeStaleGrokInstalls(dataDir: string, onError: (error: unknown) => void = () => {}): void {
  removeStalePinnedInstalls(GROK_INSTALL_SPEC, dataDir, onError);
}
