/**
 * Installing Codex (epic 12 entries 4 to 6): the pinned `codex-acp` adapter
 * and the Codex CLI it bundles, into `<dataDir>/agents/codex/` by the shared
 * pinned-npm installer (`pinned-npm/install.ts`, the one Claude Code uses):
 * `npm ci` from the pinned lock, `--ignore-scripts`, every tarball's integrity
 * checked, nothing installed globally, `~/.codex` never read or written. The
 * lock's per-platform `@openai/codex-<os>-<arch>` packages carry the Codex
 * binary, so an install always keeps the optional dependencies (npm picks
 * this computer's by their `os` and `cpu`); the adapter never gets `CODEX_PATH`.
 */
import { existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { CODEX, CODEX_ADAPTER_PACKAGE } from '../acp-codex/constants.js';
import {
  entryIn,
  installPinnedNpm,
  pinnedVersionOf,
  removeStalePinnedInstalls,
  type AdapterLock,
  type AdapterPins,
  type InstallPinnedNpmOptions,
  type PinnedNpmSpec,
} from '../pinned-npm/install.js';
import pinnedLock from './pins/package-lock.json' with { type: 'json' };
import pinnedManifest from './pins/package.json' with { type: 'json' };

/** `<dataDir>/agents/codex`: the installed adapters and the temp folders an install works in. */
export const CODEX_DIR = join('agents', 'codex');

/** The pinned adapter and Codex CLI (`pins/`, generated by `scripts/agent-pins.mjs --agent codex`). */
export const CODEX_PINS: AdapterPins = { packageJson: pinnedManifest, lock: pinnedLock as AdapterLock };

/** `adapter-<version>`; a prerelease (`0.0.0-fixture`) is a version too. */
const INSTALLED_FOLDER = /^adapter-(\d+\.\d+\.\d+(?:-[0-9A-Za-z.]+)?)$/;

/** Whether the lock holds the Codex CLI's platform binary packages (the real pins do; a test fixture needn't). */
const locksBinaries = (lock: AdapterLock) => Object.keys(lock.packages).some((path) => path.startsWith('node_modules/@openai/codex-'));

/** Whether npm put this computer's Codex binary package in `project`. */
function hasBinary(project: string): boolean {
  try {
    return readdirSync(join(project, 'node_modules', '@openai')).some((name) => name.startsWith('codex-'));
  } catch {
    return false;
  }
}

/** How Codex's adapter is installed, for the shared installer. */
export const CODEX_INSTALL_SPEC: PinnedNpmSpec = {
  displayName: CODEX,
  dir: CODEX_DIR,
  packageName: CODEX_ADAPTER_PACKAGE,
  entry: ['dist', 'index.js'],
  folderName: (version) => `adapter-${version}`,
  isInstalledFolder: (name) => INSTALLED_FOLDER.test(name),
  binary: { locked: locksBinaries, present: hasBinary },
};

/** The adapter version `pins` installs. */
export function pinnedCodexVersion(pins: AdapterPins = CODEX_PINS): string {
  return pinnedVersionOf(CODEX_INSTALL_SPEC, pins);
}

export interface InstalledCodex {
  /** The adapter's entry script, `…/node_modules/@agentclientprotocol/codex-acp/dist/index.js`. */
  path: string;
  version: string;
}

/**
 * The adapter an install put in `<dataDir>/agents/codex/`, or `undefined`:
 * the pinned version first, then the newest other (a release that bumps the
 * pin keeps an earlier install working).
 */
export function installedCodex(dataDir: string, pins: AdapterPins = CODEX_PINS): InstalledCodex | undefined {
  const dir = join(dataDir, CODEX_DIR);
  let names: string[];
  try {
    names = readdirSync(dir);
  } catch {
    return undefined;
  }
  const pinned = pinnedCodexVersion(pins);
  return names
    .map((name) => ({ name, match: INSTALLED_FOLDER.exec(name) }))
    .filter((entry): entry is { name: string; match: RegExpExecArray } => entry.match !== null)
    .map(({ name, match }) => ({ path: entryIn(CODEX_INSTALL_SPEC, join(dir, name)), version: match[1]! }))
    .filter((adapter) => existsSync(adapter.path))
    .sort((a, b) => {
      if ((a.version === pinned) !== (b.version === pinned)) return a.version === pinned ? -1 : 1;
      return b.version.localeCompare(a.version, 'en', { numeric: true });
    })[0];
}

export type InstallCodexOptions = Omit<InstallPinnedNpmOptions, 'pins' | 'withBinary'> & { pins?: AdapterPins | undefined };

/**
 * Installs the pinned adapter and Codex CLI under `<dataDir>/agents/codex/`,
 * reporting progress; rejects with an `AgentSetupError` in plain words,
 * leaving nothing half installed (the shared installer's rules).
 */
export async function installCodex(options: InstallCodexOptions): Promise<InstalledCodex> {
  return installPinnedNpm(CODEX_INSTALL_SPEC, { ...options, pins: options.pins ?? CODEX_PINS, withBinary: true });
}

/** Removes the `.install-*` folders a crashed or killed install left in `<dataDir>/agents/codex/` (server start). */
export function removeStaleCodexInstalls(dataDir: string, onError: (error: unknown) => void = () => {}): void {
  removeStalePinnedInstalls(CODEX_INSTALL_SPEC, dataDir, onError);
}
